image: Visual Studio 2019

before_build:
  - nuget restore 4thSemester/IntroductionFSharp/HW2/HW2.sln

build:
  project: 4thSemester/IntroductionFSharp/HW2/HW2.sln

test_script:
  - nunit3-console 4thSemester/IntroductionFSharp/HW2/HW2.sln \
    --result=myresults.xml;format=AppVeyor